-- TABLE : macro_geo_latest
-- 1 mesure DAX

Macro Risk Index =
VAR inflation_norm = DIVIDE( macro_geo_latest[inflation_pct], 10, 0 ) * 40
VAR unemp_norm     = DIVIDE( macro_geo_latest[unemployment_pct], 20, 0 ) * 30
VAR lending_norm   = DIVIDE( COALESCE( macro_geo_latest[lending_rate_pct], 5 ), 50, 0 ) * 30
RETURN ROUND( inflation_norm + unemp_norm + lending_norm, 1 )
